version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
          name: install dependencies
          command: |
            make install
            
      
      - run:
          name: run lint
          command: |
            make lint