apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity-capstone #cluster name
  region: us-west-2 #desired region

nodeGroups:
  - name: node-group-1 #cluster node group name
    instanceType: t2.medium #desired instance type
    desiredCapacity: 3 #desired nodes count / capacity
    ssh:
      allow: false